### ISSUE TITLE
owl:equivalent classes from dbr are not valid turtle?

### ISSUE THREAD

**Issue by mathib** [w3c-lbd-cg/product#10]
Whenever some dbpedia class is mentioned with curly brackets in short notation (e.g. `dbr:Table_(furniture)`), the Turtle seems not valid anymore (tested with http://ttl.summerofcode.be/ and while importing in a Stardog DB). This can be solved by placing the complete URI instead (e.g. `<http://dbpedia.org/resource/Table_(furniture)>`).

This issue occurs once in prod_furnishing.ttl, and three times in prod_mep.ttl

**Comment by pipauwel** [comment]
This should be fixed now. Can you check?

**Comment by mathib** [comment]
OK, this can be closed
