### ISSUE TITLE
Substantial overlap to existing product data modelling approches

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [w3c-lbd-cg/product#6]
Hi!

There exists a substantial overlap of the PRODUCT ontology modelling effort with existing approaches to publish product data in AEC industriy on the web.

E.g.:

[FreeClassOWL](http://www.freeclass.eu/freeclass_v1.html)
[BauDataWeb](http://semantic.eurobau.com/)
[eClassOWL](http://www.heppnetz.de/projects/eclassowl/)
[UNSPSC](https://www.unspsc.org/)
[proficl@ss](http://www.proficlass.de/)
[omniclass](http://ominclass.org)
[BAUKOM](https://doi.org/10.1016/j.autcon.2015.05.007)
[PPBIM](http://cobuilder.fr/la-norme-xp-p07-150-en-france/) [and](https://www.boutique.afnor.org/norme/xp-p07-150/proprietes-des-produits-et-systemes-utilises-en-construction-definition-des-proprietes-methodologie-de-creation-et-de-gestion/article/820819/fa184671)
[VDI3805](https://www.vdi.de/technik/fachthemen/bauen-und-gebaeudetechnik/fachbereiche/technische-gebaeudeausruestung/richtlinienarbeit/richtlinienreihe-vdi-3805-produktdatenaustausch-in-der-tga/) and [ISO757](https://www.iso.org/standard/57613.html)
[CoClass (Sweden)](https://coclass.byggtjanst.se/sv/loggain?ReturnUrl=%2f)
[ISO12006-2](https://www.iso.org/standard/61753.html)
[NIST PDTO](https://www.nist.gov/publications/product-data-sheet-ontology)
[NBS PDT](https://toolkit.thenbs.com/articles/pdts)
[VVS Kataloget - National, Denmark](http://www.branchehuset.dk/english_vvskataloget.php)
[CBNL - National, Netherlands](http://public.cbnl.org/)

See also review and paper in [[1](https://www.researchgate.net/publication/307865586_SemCat_Publishing_and_Accessing_Building_Product_Information_as_Linked_Data?_iepl%5BviewId%5D=Oy07VM61Qjm7LRUXzBDFSy4c&_iepl%5BprofilePublicationItemVariant%5D=default&_iepl%5Bcontexts%5D%5B0%5D=prfpi&_iepl%5BtargetEntityId%5D=PB%3A307865586&_iepl%5BinteractionType%5D=publicationTitle)]

Open questions are:

- How to stipulate further use of linked data technologies for the distribution of product data from AEC/FM industry over the web?
- Is there a need for the PRODUCT ontology modelling effort?

[1] Gudnason, G. and Pauwels, P. _SemCat: Publishing and Accessing Building Product Information as Linked Data Conference Paper_ · September 2016, Conference: ECPPM 2016, 11th European Conference on Product and Process Modelling, At Limasol, Cyprus

**Comment by pipauwel** [comment]
There is overlap with existing product modelling approaches, yes. The main idea for this product ontology is that explicitly present building elements (walls, windows, etc.) in specific existing buildings can be modelled using this ontology (not classified - cfr. FreeClass and all), in inspiration of IFC. From that placeholder, further links to other product data and classifications can be added as instance data, thereby using many of the existing product modelling approaches in a linked data fashion.
