### ISSUE TITLE
Linking PRODUCT and BOT ontologies

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [w3c-lbd-cg/product#7]
It remains unclear if and how to link PRODUCT and BOT ontologies.

Options:

> product:Product rdfs:subClassOf bot:Element .

>...

**Comment by mathib** [comment]
No decision has been taken yet? Seems logical to make product:Product a subclass of bot:Element

**Comment by pipauwel** [comment]
The decision taken months ago, in one of the online meetings, was to keep bot:Element and product:Product separate unrelated classes, and not subclass one underneath the other. In the instance data, it is advised to name specific elements (walls, windows, etc.) bot:Element AND product:Product. But this is up to the end user and/or implementer.
